config/routes.rb
Rails.application.routes.draw do
  get 'search/show'

  get 'search/results'

  get 'search/show'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'homepage/index'
  get 'homepage_url' => 'homepage/index'
  post '/courses/enrole'
  resources :subjects
  resources :instructors
  resources :courses
  resources :courses

  root 'homepage#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coursecatalog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-3">
      <h3>Course Catalog</h3>
      <div id="header">
        <% if signed_in? %>
          <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
        <% else %>
          <%= link_to t(".sign_in"), sign_in_path %>
        <% end %>
      </div>
      <%= link_to "Home", root_path %>
      <%= link_to "Subjects", subjects_path %>
      <%= link_to "Courses", courses_path %>
      <%= link_to "Instructors", instructors_path %>
      <%= link_to "Search", '/search/show' %>
    </div>
    <div class="col-xs-9">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>